apps/servicos/urls.py
from django.urls import path
from .views import (
    CategoriaServicoListView,
    CategoriaServicoCreateView,
    CategoriaServicoUpdateView,
    CategoriaServicoDeleteView,
    ServicoListView,
    ServicoCreateView,
    ServicoUpdateView,
    ServicoDeleteView,


)

app_name = 'servicos'

urlpatterns = [

    path('', ServicoListView.as_view(), name='lista_servicos'),
    path('novo/', ServicoCreateView.as_view(), name='novo_servico'),
    path('atualizar/<int:pk>/', ServicoUpdateView.as_view(), name='atualizar_servico'),
    path('deletar/<int:pk>/', ServicoDeleteView.as_view(), name='deletar_servico'),

    path('categoria/', CategoriaServicoListView.as_view(), name='lista_categoria_servico'),
    path('categoria/nova/', CategoriaServicoCreateView.as_view(), name='nova_categoria_servico'),
    path('categoria/atualizar/<int:pk>/', CategoriaServicoUpdateView.as_view(), name='atualizar_categoria_servico'),
    path('deletar/categoria/<int:pk>/', CategoriaServicoDeleteView.as_view(), name='deletar_categoria_servico'),

]

vm_acessoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.dashboard import urls as dashboard_urls
from apps.orcamentos import urls as orcamentos_urls
from apps.clientes import urls as cliente_urls
from apps.produtos import urls as produtos_urls
from apps.home import urls as home_urls
from apps.servicos import urls as servicos_url
from apps.propostas import urls as propostas_url
from apps.api import urls as api_urls

urlpatterns = [
    path('api/v1/', include(api_urls)),
    path('propostas/', include(propostas_url)),
    path('servicos/', include(servicos_url)),
    path('home/', include(home_urls)),
    path('orcamentos/', include(orcamentos_urls)),
    path('clientes/', include(cliente_urls)),
    path('produtos/', include(produtos_urls)),
    path('', include(dashboard_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/servicos/models.py
from django.db import models
from apps.core.models import Base


class CategoriaServico(Base):
    nome = models.CharField("Nome", max_length=100, unique=True)

    class Meta:
        verbose_name = 'Categoria Serviço'
        verbose_name_plural = 'Categorias Serviços'
        ordering = ['-created']

    def __str__(self):
        return self.nome


class Servico(models.Model):
    categoria_servico = models.ForeignKey(
        CategoriaServico, on_delete=models.CASCADE,
        verbose_name='Serviço',
        related_name='categoria_servico'
    )
    descricao = models.TextField('Descrição')
    preco_compra = models.DecimalField('Valor', decimal_places=2, max_digits=8, default=0)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Serviços'
        verbose_name_plural = 'Serviços'
        ordering = ['-created']

    def __str__(self):
        return self.descricao

apps/servicos/forms.py
from django.forms import ModelForm, Textarea
from .models import Servico, CategoriaServico
from bootstrap_modal_forms.forms import BSModalModelForm


class ServicoForm(BSModalModelForm):
    class Meta:
        model = Servico
        fields = '__all__'
        widgets = {
            "descricao": Textarea(attrs={"cols": 20, "rows": 5}),
        }


class CategoriaServicoForm(BSModalModelForm):
    class Meta:
        model = CategoriaServico
        fields = '__all__'

apps/servicos/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Servico, CategoriaServico
from .forms import ServicoForm, CategoriaServicoForm

from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView,
    BSModalReadView
)


class ServicoListView(LoginRequiredMixin, ListView):
    model = Servico
    template_name = 'servicos/servico_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_menu_servico'] = True
        context['open_menu_servico'] = True
        context['active_servico'] = True
        return context


class ServicoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'servicos/novo_servico.html'
    form_class = ServicoForm
    success_message = 'Success:Servico Criado.'
    success_url = reverse_lazy('servicos:lista_servicos')


class ServicoUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Servico
    template_name = 'servicos/atualizar_servico.html'
    form_class = ServicoForm
    success_message = 'Success: Serviço Atualizado.'
    success_url = reverse_lazy('servicos:lista_servicos')


class ServicoDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Servico
    template_name = 'servicos/delete_servico.html'
    success_message = 'Success: Fornecedor excluído com sucesso.'
    success_url = reverse_lazy('servicos:lista_servicos')


class CategoriaServicoListView(LoginRequiredMixin, ListView):
    model = CategoriaServico
    template_name = 'servicos/categoria_servico_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_menu_servico'] = True
        context['open_menu_servico'] = True
        context['active_categoria_servico'] = True
        return context


class CategoriaServicoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'servicos/nova_categoria_servico.html'
    form_class = CategoriaServicoForm
    success_message = 'Success: Tipo de Serviço Criado.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')


class CategoriaServicoUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = CategoriaServico
    template_name = 'servicos/atualizar_categoria_servico.html'
    form_class = CategoriaServicoForm
    success_message = 'Success: Tipo Servico Atualizado.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')


class CategoriaServicoDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = CategoriaServico
    template_name = 'servicos/delete_categoria_servico.html'
    success_message = 'Success: Tipo de servico excluído com sucesso.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')

templates/servicos/atualizar_categoria_servico.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Categoria Serviço</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}

        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/atualizar_mao_de_obra.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Mão De Obra</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}

        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/atualizar_servico.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Mão De Obra</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}

        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/categoria_servico_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block titulo_pagina %}Categorias Serviços{% endblock titulo_pagina %}

{% block content %}
    <div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <!-- Modal 2 with id="modal" -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <!-- Create book button -->

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categoria Serviço</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Servicos</li>
                            <li class="breadcrumb-item active">Categoria</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button id="create-maoDeObra" class="btn btn-primary" type="button" name="button">Nova Categoria</button>
                            </div>
                            <!-- ./card-header -->
                            <div class="card-body">
                             {% include 'servicos/includes/_tipo_servicos_table.html' %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}


{% block js %}

    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $("#create-maoDeObra").modalForm({
                formURL: "{% url 'servicos:nova_categoria_servico' %}"
            });

            var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

            function updateMaoDeObraModalForm() {
            $(".update-mao-de-obra").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: false,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "categoria/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateMaoDeObraModalForm();

        function reinstantiateModalForms() {

        updateMaoDeObraModalForm();

      }

       function deleteCategoriaForm() {
            $(".delete-categoria").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteCategoriaForm();

        });
    </script>


{% endblock js %}

templates/servicos/delete_categoria_servico.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Categoria</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir a categoria
      <strong>{{ object.nome }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/servicos/delete_mao_de_obra.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Mão de Obra</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir o mao de obra com o nome
      <strong>{{ object.descricao }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/servicos/delete_servico.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Mão de Obra</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir o mao de obra com o nome
      <strong>{{ object.descricao }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/servicos/nova_categoria_servico.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Nova Categoria Serviço</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
   <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/nova_mao_de_obra.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Nova Mão de Obra</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
   <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/novo_servico.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Novo Serviço</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
   <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/servicos/servico_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block titulo_pagina %}Serviços{% endblock titulo_pagina %}

{% block content %}
    <div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <!-- Modal 2 with id="modal" -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <!-- Create book button -->

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Serviços</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Servicos</li>
                            <li class="breadcrumb-item active">Lista de Serviços</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button id="create-maoDeObra" class="btn btn-primary" type="button" name="button">Novo Serviço</button>
                            </div>
                            <!-- ./card-header -->
                            <div class="card-body">
                             {% include 'servicos/includes/_servicos_table.html' %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}


{% block js %}

    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $("#create-maoDeObra").modalForm({
                formURL: "{% url 'servicos:novo_servico' %}"
            });

            var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

            function updateMaoDeObraModalForm() {
            $(".update-mao-de-obra").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: false,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "categoria/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateMaoDeObraModalForm();

        function reinstantiateModalForms() {

        updateMaoDeObraModalForm();

      }

       function deleteCategoriaForm() {
            $(".delete-categoria").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteCategoriaForm();

        });
    </script>


{% endblock js %}