apps/produtos/urls.py
from django.urls import path

from .views import (FornecedorCreateView, FornecedorListView, FornecedorUpdateView, FornecedorDeleteView,
                    CategoriaCreateView, CategoriasListView, CategoriaUpdateView, CategoriaDeleteView,
                    ProdutoListView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView, ProdutoReadView
                    )

app_name = 'produtos'

urlpatterns = [
    path('', ProdutoListView.as_view(), name='lista_produto'),
    path('novo/', ProdutoCreateView.as_view(), name='novo_produto'),
    path('editar/<int:pk>/', ProdutoUpdateView.as_view(), name='atualizar_produto'),
    path('read/<int:pk>', ProdutoReadView.as_view(), name='read_produto'),
    path('delete/<int:pk>/', ProdutoDeleteView.as_view(), name='delete_produto'),

    path('fornecedor/', FornecedorListView.as_view(), name='lista_fornecedor'),
    path('fornecedor/novo/', FornecedorCreateView.as_view(), name='novo_fornecedor'),
    path('fornecedor/editar/<int:pk>/', FornecedorUpdateView.as_view(), name='atualizar_fornecedor'),
    path('fornecedor/delete/<int:pk>/', FornecedorDeleteView.as_view(), name='delete_fornecedor'),

    path('categorias/', CategoriasListView.as_view(), name='lista_categorias'),
    path('categoria/nova/', CategoriaCreateView.as_view(), name='nova_categoria'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='atualizar_categoria'),
    path('categoria/delete/<int:pk>/', CategoriaDeleteView.as_view(), name='delete_categoria'),
]

vm_acessoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.dashboard import urls as dashboard_urls
from apps.orcamentos import urls as orcamentos_urls
from apps.clientes import urls as cliente_urls
from apps.produtos import urls as produtos_urls
from apps.home import urls as home_urls
from apps.servicos import urls as servicos_url
from apps.propostas import urls as propostas_url
from apps.api import urls as api_urls

urlpatterns = [
    path('api/v1/', include(api_urls)),
    path('propostas/', include(propostas_url)),
    path('servicos/', include(servicos_url)),
    path('home/', include(home_urls)),
    path('orcamentos/', include(orcamentos_urls)),
    path('clientes/', include(cliente_urls)),
    path('produtos/', include(produtos_urls)),
    path('', include(dashboard_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/produtos/models.py
from django.db import models
from apps.core.models import Base


class Fornecedor(Base):
    class Meta:
        verbose_name = 'Fornecedo'
        verbose_name_plural = 'Fornecedores'
        ordering = ['nome']


class Categoria(Base):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['nome']


class Produto(Base):
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
        verbose_name='Categoria',
        related_name='p_categoria'
    )
    fornecedor = models.ForeignKey(
        Fornecedor,
        on_delete=models.CASCADE,
        verbose_name='Fornecedor',
        related_name='p_fornecedor'
    )
    preco_compra = models.DecimalField('Preço de Compra', decimal_places=2, max_digits=8)

    def __str__(self):
        return f"{self.nome}--R$:{self.preco_compra}"

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['nome']

apps/produtos/forms.py
from django import forms

from .models import Fornecedor, Categoria, Produto
from bootstrap_modal_forms.forms import BSModalModelForm


class FornecedorForm(BSModalModelForm):
    class Meta:
        model = Fornecedor
        fields = '__all__'


class CategoriaForm(BSModalModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'


class ProdutoForm(BSModalModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(ProdutoForm, self).__init__(*args, **kwargs)
    #
    #     for visible in self.visible_fields():
    #         if visible.field.widget.input_type == 'select':
    #             visible.field.widget.attrs['class'] = 'select2bs4'

    class Meta:
        model = Produto
        fields = '__all__'

apps/produtos/views.py
from django.urls import reverse_lazy
from .forms import FornecedorForm, CategoriaForm, ProdutoForm
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Fornecedor, Categoria, Produto
from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView,
    BSModalReadView
)


class FornecedorListView(LoginRequiredMixin, ListView):
    model = Fornecedor
    template_name = 'produtos/fornecedor_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_open_produto'] = True
        context['active_fornecedores'] = True
        return context


class FornecedorCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'produtos/novo_fornecedor.html'
    form_class = FornecedorForm
    success_message = 'Success: Fornecedor Criado.'
    success_url = reverse_lazy('produtos:lista_fornecedor')


class FornecedorUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Fornecedor
    template_name = 'produtos/atualizar_fornecedor.html'
    form_class = FornecedorForm
    success_message = 'Success: Fornecedor Atualizado.'
    success_url = reverse_lazy('produtos:lista_fornecedor')


class FornecedorDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Fornecedor
    template_name = 'produtos/delete_fornecedor.html'
    success_message = 'Success: Fornecedor excluído com sucesso.'
    success_url = reverse_lazy('produtos:lista_fornecedor')


class CategoriasListView(LoginRequiredMixin, ListView):
    model = Categoria
    template_name = 'produtos/categoria_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_open_produto'] = True
        context['active_produto_categoria'] = True
        return context


class CategoriaCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'produtos/nova_categoria.html'
    form_class = CategoriaForm
    success_message = 'Success: Categoria Criada.'
    success_url = reverse_lazy('produtos:lista_categorias')


class CategoriaUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Categoria
    template_name = 'produtos/atualizar_categoria.html'
    form_class = CategoriaForm
    success_message = 'Success: Categoria Atualizada.'
    success_url = reverse_lazy('produtos:lista_categorias')


class CategoriaDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Categoria
    template_name = 'produtos/delete_categoria.html'
    success_message = 'Success: Categoria excluída com sucesso.'
    success_url = reverse_lazy('produtos:lista_categorias')


class ProdutoListView(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'produtos/produto_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_open_produto'] = True
        context['active_produto'] = True
        return context


class ProdutoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'produtos/novo_produto.html'
    form_class = ProdutoForm
    success_message = 'Success: Produto criado com sucesso.'
    success_url = reverse_lazy('produtos:lista_produto')


class ProdutoUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Produto
    template_name = 'produtos/atualizar_produto.html'
    form_class = ProdutoForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('produtos:lista_produto')


class ProdutoDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Produto
    template_name = 'produtos/delete_produto.html'
    success_message = 'Success: Produto Deletado.'
    success_url = reverse_lazy('produtos:lista_produto')


class ProdutoReadView(LoginRequiredMixin, BSModalReadView):
    model = Produto
    template_name = 'produtos/read_produto.html'

templates/produtos/atualizar_categoria.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Categoria</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

templates/produtos/atualizar_fornecedor.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Cliente</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

templates/produtos/atualizar_produto.html
{% load widget_tweaks %}

<form method="post" action="" novalidate>
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Atualizar Produto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% if field.widget_type == 'select' %}
        {% render_field field class="form-control select2bs4" placeholder=field.label %}
          {% else %}
           {% render_field field class="form-control" placeholder=field.label %}
      {% endif %}

        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Atualizar</button>
  </div>

</form>

<script>
    $(function () {
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

templates/produtos/categoria_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block titulo_pagina %}Categorias{% endblock titulo_pagina %}

{% block content %}
    <div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <!-- Modal 2 with id="modal" -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <!-- Create book button -->

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categorias</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Categorias</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button id="create-categoria" class="btn btn-primary" type="button" name="button">Nova Categoria</button>
                            </div>
                            <!-- ./card-header -->
                            <div class="card-body">
                             {% include 'produtos/includes/_categoria_table.html' %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}

{% block js %}

    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $("#create-categoria").modalForm({
                formURL: "{% url 'produtos:nova_categoria' %}"
            });

            var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

            function updateCategoriaModalForm() {
            $(".update-categoria").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: false,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "categoria/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateCategoriaModalForm();

        function reinstantiateModalForms() {

        updateCategoriaModalForm();

      }

       function deleteCategoriaForm() {
            $(".delete-categoria").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteCategoriaForm();

        });
    </script>


{% endblock js %}

templates/produtos/delete_categoria.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Categoria</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir a categoria com o nome
      <strong>{{ categoria.nome }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/produtos/delete_fornecedor.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Fornecedor</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir o fornecedor com o nome
      <strong>{{ fornecedor.nome }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/produtos/delete_produto.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Deletar Produto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza de que deseja excluir o produto com o nome
      <strong>{{ produto.nome }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

templates/produtos/fornecedor_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo_pagina %}Fornecedores{% endblock titulo_pagina %}

{% block content %}
    <div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <!-- Modal 2 with id="modal" -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <!-- Create book button -->

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Fornecedores</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Fornecedores</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button id="create-fornecedor" class="btn btn-primary" type="button" name="button">Novo Fornecedor</button>
                            </div>
                            <!-- ./card-header -->
                            <div class="card-body">
                             {% include 'produtos/includes/_fornecedor_table.html' %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}

{% block js %}

    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $("#create-fornecedor").modalForm({
                formURL: "{% url 'produtos:novo_fornecedor' %}"
            });

            var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

            function updateFornecedorModalForm() {
            $(".update-cliente").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: false,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "fornecedor/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateFornecedorModalForm();

        function reinstantiateModalForms() {

        updateFornecedorModalForm();

      }

       function deleteFornecedorForm() {
            $(".delete-fornecedor").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteFornecedorForm();

        });
    </script>


{% endblock js %}

templates/produtos/produto_list.html
{% extends 'core/base.html' %}
{% load static %}


{% block titulo_pagina %}Produtos{% endblock titulo_pagina %}

{% block css %}
    <link rel="stylesheet" href="{% static 'core/plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">



    <link rel="stylesheet" href="{% static 'core/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">


    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
{% endblock css %}

{% block content %}
    <div class="modal fade" id="create-modal"  role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <!-- Modal 2 with id="modal" -->
    <div class="modal fade"  role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <!-- Create book button -->

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Produtos</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Produtos</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button id="create-produto" class="btn btn-primary" type="button" name="button">Novo Produto</button>
                            </div>
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Produtos</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    {% include 'produtos/includes/_table_lista_produtos.html' %}
                                </div>
                                <!-- /.card-body -->
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}

{% block js %}

    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    <script src="{% static 'core/plugins/select2/js/select2.full.min.js' %}"></script>


    <script src="{% static 'core/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'core/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>


    <script type="text/javascript">
        $(document).ready(function() {

            $("#create-produto").modalForm({
                formURL: "{% url 'produtos:novo_produto' %}"
            });

            var asyncSuccessMessageUpdate = [
                "<div ",
                "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
                "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
                "Success: Book was updated.",
                "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
                "<span aria-hidden='true'>&times;</span>",
                "</button>",
                "</div>",
                "<script>",
                "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
                "<\/script>"
            ].join("");

            function updateProdutoModalForm() {
                $(".update-produto").each(function () {
                    $(this).modalForm({
                        formURL: $(this).data("form-url"),
                        asyncUpdate: false,
                        asyncSettings: {
                            closeOnSubmit: false,
                            successMessage: asyncSuccessMessageUpdate,
                            dataUrl: "produto/",
                            dataElementId: "#books-table",
                            dataKey: "table",
                            addModalFormFunction: reinstantiateModalForms
                        }
                    });
                });
            }
            updateProdutoModalForm();

            function reinstantiateModalForms() {

                updateProdutoModalForm();

            }

            function deleteProdutoForm() {
                $(".delete-produto").each(function () {
                    $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
                });
            }
            deleteProdutoForm();

            function readProdutoModalForm() {
                $(".read-produto").each(function () {
                    $(this).modalForm({formURL: $(this).data("form-url")});
                });
            }
            readProdutoModalForm();

        });
    </script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print"],
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.13.2/i18n/pt-BR.json'
                },
                scrollY: '50vh',
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>


{% endblock js %}