apps/servicos/urls.py
from django.urls import path
from .views import (
    CategoriaServicoListView,
    CategoriaServicoCreateView,
    CategoriaServicoUpdateView,
    CategoriaServicoDeleteView,
    ServicoListView,
    ServicoCreateView,
    ServicoUpdateView,
    ServicoDeleteView,


)

app_name = 'servicos'

urlpatterns = [

    path('', ServicoListView.as_view(), name='lista_servicos'),
    path('novo/', ServicoCreateView.as_view(), name='novo_servico'),
    path('atualizar/<int:pk>/', ServicoUpdateView.as_view(), name='atualizar_servico'),
    path('deletar/<int:pk>/', ServicoDeleteView.as_view(), name='deletar_servico'),

    path('categoria/', CategoriaServicoListView.as_view(), name='lista_categoria_servico'),
    path('categoria/nova/', CategoriaServicoCreateView.as_view(), name='nova_categoria_servico'),
    path('categoria/atualizar/<int:pk>/', CategoriaServicoUpdateView.as_view(), name='atualizar_categoria_servico'),
    path('deletar/categoria/<int:pk>/', CategoriaServicoDeleteView.as_view(), name='deletar_categoria_servico'),

]

vm_acessoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.dashboard import urls as dashboard_urls
from apps.orcamentos import urls as orcamentos_urls
from apps.clientes import urls as cliente_urls
from apps.produtos import urls as produtos_urls
from apps.home import urls as home_urls
from apps.servicos import urls as servicos_url
from apps.propostas import urls as propostas_url
from apps.api import urls as api_urls

urlpatterns = [
    path('api/v1/', include(api_urls)),
    path('propostas/', include(propostas_url)),
    path('servicos/', include(servicos_url)),
    path('home/', include(home_urls)),
    path('orcamentos/', include(orcamentos_urls)),
    path('clientes/', include(cliente_urls)),
    path('produtos/', include(produtos_urls)),
    path('', include(dashboard_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/servicos/models.py
from django.db import models
from apps.core.models import Base


class CategoriaServico(Base):
    nome = models.CharField("Nome", max_length=100, unique=True)

    class Meta:
        verbose_name = 'Categoria Serviço'
        verbose_name_plural = 'Categorias Serviços'
        ordering = ['-created']

    def __str__(self):
        return self.nome


class Servico(models.Model):
    categoria_servico = models.ForeignKey(
        CategoriaServico, on_delete=models.CASCADE,
        verbose_name='Serviço',
        related_name='categoria_servico'
    )
    descricao = models.TextField('Descrição')
    preco_compra = models.DecimalField('Valor', decimal_places=2, max_digits=8, default=0)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Serviços'
        verbose_name_plural = 'Serviços'
        ordering = ['-created']

    def __str__(self):
        return self.descricao

apps/servicos/forms.py
from django.forms import ModelForm, Textarea
from .models import Servico, CategoriaServico
from bootstrap_modal_forms.forms import BSModalModelForm


class ServicoForm(BSModalModelForm):
    class Meta:
        model = Servico
        fields = '__all__'
        widgets = {
            "descricao": Textarea(attrs={"cols": 20, "rows": 5}),
        }


class CategoriaServicoForm(BSModalModelForm):
    class Meta:
        model = CategoriaServico
        fields = '__all__'

apps/servicos/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Servico, CategoriaServico
from .forms import ServicoForm, CategoriaServicoForm

from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView,
    BSModalReadView
)


class ServicoListView(LoginRequiredMixin, ListView):
    model = Servico
    template_name = 'servicos/servico_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_menu_servico'] = True
        context['open_menu_servico'] = True
        context['active_servico'] = True
        return context


class ServicoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'servicos/novo_servico.html'
    form_class = ServicoForm
    success_message = 'Success:Servico Criado.'
    success_url = reverse_lazy('servicos:lista_servicos')


class ServicoUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Servico
    template_name = 'servicos/atualizar_servico.html'
    form_class = ServicoForm
    success_message = 'Success: Serviço Atualizado.'
    success_url = reverse_lazy('servicos:lista_servicos')


class ServicoDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Servico
    template_name = 'servicos/delete_servico.html'
    success_message = 'Success: Fornecedor excluído com sucesso.'
    success_url = reverse_lazy('servicos:lista_servicos')


class CategoriaServicoListView(LoginRequiredMixin, ListView):
    model = CategoriaServico
    template_name = 'servicos/categoria_servico_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_menu_servico'] = True
        context['open_menu_servico'] = True
        context['active_categoria_servico'] = True
        return context


class CategoriaServicoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'servicos/nova_categoria_servico.html'
    form_class = CategoriaServicoForm
    success_message = 'Success: Tipo de Serviço Criado.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')


class CategoriaServicoUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = CategoriaServico
    template_name = 'servicos/atualizar_categoria_servico.html'
    form_class = CategoriaServicoForm
    success_message = 'Success: Tipo Servico Atualizado.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')


class CategoriaServicoDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = CategoriaServico
    template_name = 'servicos/delete_categoria_servico.html'
    success_message = 'Success: Tipo de servico excluído com sucesso.'
    success_url = reverse_lazy('servicos:lista_categoria_servico')

templates/servicos/includes/_servicos_table.html
<table id="books-table" class="table table-bordered">
    <thead>
    <tr>
        <th>Categoria</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th>Ação</th>

    </tr>
    </thead>
    <tbody>
    {% for item in object_list %}
        <tr>
            <td>{{ item.categoria_servico }}</td>
            <td>{{ item.descricao }}</td>
            <td>{{ item.preco_compra }}</td>


            <td>

                <button type="button" class="update-mao-de-obra btn btn-sm btn-primary" data-form-url="{% url 'servicos:atualizar_servico' item.pk %}">
                    <span class="fas fa-pencil-alt"></span>
                </button>
                <button type="button" class="delete-categoria btn btn-sm btn-danger" data-form-url="{% url 'servicos:deletar_servico' item.pk %}">
                    <span class="fa fa-trash"></span>
                </button>
            </td>
        </tr>

    {% endfor %}

    </tbody>
</table>

templates/servicos/includes/_tipo_servicos_table.html
<table id="books-table" class="table table-bordered">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Ação</th>

    </tr>
    </thead>
    <tbody>
    {% for item in object_list %}
        <tr>
            <td>{{ item.nome }}</td>
            <td>

                <button type="button" class="update-mao-de-obra btn btn-sm btn-primary" data-form-url="{% url 'servicos:atualizar_categoria_servico' item.pk %}">
                    <span class="fas fa-pencil-alt"></span>
                </button>
                <button type="button" class="delete-categoria btn btn-sm btn-danger" data-form-url="{% url 'servicos:deletar_categoria_servico' item.pk %}">
                    <span class="fa fa-trash"></span>
                </button>
            </td>
        </tr>

    {% endfor %}

    </tbody>
</table>