apps/propostas/urls.py
from django.urls import path
from .views import (PropostaView, NovaPropostaView, ListaDePropostas, NovaPropostaFormView, ProstaDetalhe,
                    GerarPdfProposta)

app_name = 'proposta'

urlpatterns = [

    path('', ListaDePropostas.as_view(), name='proposta_lista'),
    #path('<int:proposta_id>/', PropostaView.as_view(), name='proposta_detalhe'),
    path('nova/', NovaPropostaFormView.as_view(), name='nova_proposta'),
    path('buscar/<str:orcamento_id>/', NovaPropostaView.as_view(), name='proposta_redirect'),
    path('<int:pk>/', ProstaDetalhe.as_view(), name='proposta_detalhe'),
    path('pdf/<int:id>/', GerarPdfProposta.as_view(), name='proposta_pdf'),

]

vm_acessoria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from apps.dashboard import urls as dashboard_urls
from apps.orcamentos import urls as orcamentos_urls
from apps.clientes import urls as cliente_urls
from apps.produtos import urls as produtos_urls
from apps.home import urls as home_urls
from apps.servicos import urls as servicos_url
from apps.propostas import urls as propostas_url
from apps.api import urls as api_urls

urlpatterns = [
    path('api/v1/', include(api_urls)),
    path('propostas/', include(propostas_url)),
    path('servicos/', include(servicos_url)),
    path('home/', include(home_urls)),
    path('orcamentos/', include(orcamentos_urls)),
    path('clientes/', include(cliente_urls)),
    path('produtos/', include(produtos_urls)),
    path('', include(dashboard_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/propostas/models.py
from apps.core.models import Base
from django.db import models
from apps.orcamentos.models import Orcamento
from django.urls import reverse
from apps.core.gerador_pix import gerador_proposta_pix
from django.db.models import signals


class Proposta(models.Model):
    codigo = models.CharField('Codigo', max_length=30, unique=True)
    finalizado = models.BooleanField('Finalizado', default=False)
    orcamento = models.OneToOneField(
        Orcamento,
        on_delete=models.CASCADE,
        verbose_name='Orcamento',
        related_name='proposta_orcamento'
    )
    desconto_real = models.DecimalField('Desconto', decimal_places=2, max_digits=8, default=0, null=True, blank=True)
    desconto_porcentagem = models.DecimalField('Porcentagem', decimal_places=2, max_digits=8, null=True, blank=True, editable=False)
    total = models.DecimalField('Total', decimal_places=2, max_digits=8, null=True, blank=True)
    valor_entrada = models.DecimalField('Valor da Entrada', decimal_places=2, max_digits=8, null=True, blank=True)
    qr_code = models.ImageField('QRcode', upload_to='qrcode/%Y/%m/%d', null=True, blank=True)
    validade = models.DateField('Validade', null=True, blank=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Proposta'
        verbose_name_plural = 'Propostas'
        ordering = ['-created']

    def __str__(self):
        return self.codigo

    def get_absolute_url(self):
        return reverse('proposta:proposta_detalhe', kwargs={'pk': self.id})


def proposta_pix(sender, instance, signal, *args, **kwargs):
    proposta = instance
    if proposta.valor_entrada:
        instance.qr_code = gerador_proposta_pix(instance.codigo, instance.valor_entrada)




signals.pre_save.connect(proposta_pix, sender=Proposta)

apps/propostas/forms.py
from django import forms
from django.forms import fields, models, formsets, widgets, CheckboxInput
from .models import Orcamento, Proposta


class OrcamentoForm(models.ModelForm):
    class Meta:
        model = Orcamento
        fields = '__all__'


class PropostaForm(models.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Proposta
        fields = ['orcamento']

    class Media:
        js = ('js/jquery.autocomplete.min.js', 'js/autocomplete-init.js',)
        css = {
            'all': ('css/jquery.autocomplete.css',),
        }


class PropostaDetalheForm(PropostaForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True
        self.fields['validade'].widget.attrs['readonly'] = True
        # self.fields['orcamento'].widget.attrs['readonly'] = True
    class Meta:
        model = Proposta
        exclude = ['orcamento', 'qr_code']
        widgets = {
            'finalizado': CheckboxInput(attrs={'weight': '15px'}),
        }

    # def save(self, commit=True):
    #     obj = super(PropostaDetalheForm, self).save(commit=False)
    #     print()

class SelectPropostaForm(forms.Form):
    orcamento = forms.ChoiceField(choices=[
    (choice.pk, choice) for choice in Orcamento.objects.all()])

apps/propostas/views.py
from django.http import HttpResponse
from django.views.generic.edit import UpdateView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from apps.core.geradorKeys import GeradorKeys
from .models import Proposta
from apps.orcamentos.models import Orcamento
from django.views.generic.list import ListView
from .forms import PropostaForm, SelectPropostaForm, PropostaDetalheForm
from django.views.generic import View
from pypix import Pix
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
import base64

class ListaDePropostas(ListView):
    model = Proposta
    template_name = 'propostas/lista_propostas.html'


class PropostaView(TemplateView):
    template_name = 'propostas/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["now"] = timezone.now()
        return context


class NovaPropostaView(RedirectView):
    permanent = False
    query_string = True
    pattern_name = "proposta_detalhe"

    def get_redirect_url(self, *args, **kwargs):
        try:
            orcamento_id = int(kwargs['orcamento_id'])
            proposta = Proposta.objects.get(orcamento_id=orcamento_id)
            return proposta.get_absolute_url()
        except Proposta.DoesNotExist:
            print()
            orcamento = Orcamento.objects.get(pk=int(kwargs['orcamento_id']))
            codigo = GeradorKeys().key_proposta(orcamento.id)
            nova_proposta = Proposta.objects.create(
                codigo=codigo,
                orcamento=orcamento,
                total=orcamento.total,
                validade=orcamento.validade,
            )
            return nova_proposta.get_absolute_url()


class NovaPropostaFormView(View):
    def get(self, request, *args, **kwargs):
        form = SelectPropostaForm()
        return render(request, 'propostas/nova_proposta.html', {'form': form})

    def post(self, request, *args, **kwargs):
        return redirect('proposta:proposta_redirect', self.request.POST['orcamento'])


class ProstaDetalhe(UpdateView):
    model = Proposta
    form_class = PropostaDetalheForm
    template_name = 'propostas/proposta.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = Proposta.objects.get(id=self.kwargs['pk'])
        context["orcamento"] = Orcamento.objects.get(proposta_orcamento=instance)
        context["proposta_id"] = instance.id
        return context



class GerarPdfProposta(View):
    template_name = 'propostas/proposta_impressao.html'

    def get(self, request, *args, **kwargs):
        proposta = Proposta.objects.get(id=kwargs['id'])
        return render(request, 'propostas/proposta_impressao.html', {'proposta': proposta})

templates/propostas/index.html
{% extends 'core/base.html' %}
{% load static %}

templates/propostas/lista_propostas.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'core/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'core/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock css %}


{% block content %}
     <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>DataTables</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">DataTables</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Código</th>
                    <th>Status</th>
                    <th>Orçamento</th>
                    <th>Entrada</th>
                    <th>Total</th>
                    <th>Data</th>
                    <th>Validade</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for proposta in object_list %}
                    <tr>
                     <td><a href="{% url 'proposta:proposta_detalhe' proposta.id %}">{{ proposta.codigo }}</a></td>
                    <td>{{ proposta.finalizado }}</td>
                    <td>{{ proposta.orcamento }}</td>
                    <td>{{ proposta.valor_entrada }}</td>
                    <td>{{ proposta.total }}</td>
                    <td>{{ proposta.created }}</td>
                    <td>{{ proposta.validade }}</td>

                  </tr>
                  {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                   <th>Código</th>
                    <th>Status</th>
                    <th>Orçamento</th>
                    <th>Entrada</th>
                    <th>Total</th>
                    <th>Data</th>
                    <th>Validade</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

{% block js %}
    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'core/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'core/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'core/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'core/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'core/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'core/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'core/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'core/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->

<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock js %}

templates/propostas/nova_proposta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/propostas/proposta.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static 'core/plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

    <link rel="stylesheet" href="{% static 'core/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">

    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
{% endblock css %}

{% block titulo_pagina %}Novo Orçamento{% endblock titulo_pagina %}
{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>General Form</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Novo Orçamento</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="card card-default">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-3">
                            <!-- Horizontal Form -->
                            <div class="card card-info">
                                <div class="card-header">
                                    <h3 class="card-title">Novo Orçamento</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form class="form-horizontal" method="post">
                                    {% csrf_token %}
                                    {{ form.media }}
                                    <div class="card-body">
                                        <div class="form-group row">
                                            <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                                                {% for error in form.non_field_errors %}
                                                    {{ error }}
                                                {% endfor %}
                                            </div>
                                        </div>
                                        {% for field in form %}
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                                    {% if field.widget_type == 'select' %}
                                                        {% render_field field.widget.attrs.readonly class="form-control select2bs4" placeholder=field.label %}
                                                    {% elif field.widget_type == 'checkbox'%}
                                                        <div class="icheck-danger d-inline">
                                                            {% render_field field  %}

                                                        </div>
                                                    {% else %}
                                                        {% render_field field class="form-control" placeholder=field.label %}
                                                    {% endif %}


                                                    <div class="{% if field.errors %} invalid{% endif %}">
                                                        {% for error in field.errors %}
                                                            <p class="help-block">{{ error }}</p>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-info">Salvar</button>
                                    </div>
                                    <!-- /.card-footer -->
                                </form>

                            </div>
                            <!-- /.card -->

                        </div>
                        <div class="col-9">
                            <div class="card card-solid">
                                <div class="card-body pb-0">
                                    <div class="row">
                                        <div class="col-12  d-flex align-items-stretch flex-column">
                                            <div class="card bg-light d-flex flex-fill">
                                                <div class="card-body pt-1">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <h2 class="lead"><b>{{ orcamento.cliente.nome }}</h2>

                                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Endereço: ------</li>
                                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Telefone #: -----</li>
                                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-envelope-open"></i></span> Email #: {{ orcamento.cliente.email }}</li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card-footer">
                                                    <div class="text-right">
                                                        <a href="#" class="btn btn-sm bg-teal">
                                                            <i class="fas fa-comments"></i>
                                                        </a>
                                                        <a href="{% url 'proposta:proposta_pdf' proposta_id %}" class="btn btn-sm btn-primary">
                                                            <i class="fas fa-user"></i> Gerar PDF
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

{% endblock content %}




{% block js %}
    <script src="{% static 'core/plugins/jquery/jquery.min.js' %}"></script>
    {% include 'core/includes/base_js_sem_jquery.html' %}

    <!-- You can alternatively load the minified version -->

    <script src="{% static 'core/plugins/select2/js/select2.full.min.js' %}"></script>




    <script>
        $(function () {
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })
        })

    </script>



{% endblock js %}